name: "WebLLM"
short_name: "WebLLM"

url: https://webllm.mlc.ai

exclude:
  - README.md
  - serve_local.sh

plugins:
  - jekyll-remote-theme

remote_theme: mlc-ai/jekyll-theme-mlc

# Gunakan 'rouge' untuk mewarnai kode jika kita ingin deploy di GitHub Pages.
highlighter: rouge

markdown: kramdown

# Struktur path untuk blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Jumlah berita di halaman utama.
front_page_news: 8

# Base pathname untuk links.
base: ""

# Membuat halaman untuk folder _projects
collections:
  projects:
    output: true

course_title: "Your Course Title Here" # Ganti dengan judul kursus yang sesuai

# Link pada navbar.
navigation:
  - title: Home
    link: /
  - title: GitHub
    link: https://github.com/mlc-ai/web-llm
