name: Build site and push to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configuring build environment
      run: |
        sudo apt-get update
        python -m pip install -U pip

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Installing dependencies
      run: |
        python -m pip install -r docs/requirements.txt
        gem install jekyll jekyll-remote-theme jekyll-sass-converter

    - name: Build and deploy site
      if: github.ref == 'refs/heads/main'
      run: |
        # Konfigurasi Git
        git config --global user.email "mlc-gh-actions-bot@nomail"
        git config --global user.name "mlc-gh-actions-bot"
        git remote set-url origin https://x-access-token:${{ secrets.MLC_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

        # Build dokumentasi
        if [ -f docs/Makefile ]; then
          cd docs
          make html
          cd ..
        else
          echo "Error: Makefile not found in docs directory."
          exit 1
        fi

        # Build Jekyll dan salin hasil build
        jekyll b -s site -d _site
        if [ -d docs/_build/html ]; then
          rm -rf _site/docs
          mkdir -p _site/docs
          cp -r docs/_build/html/* _site/docs
        else
          echo "Error: Build directory 'docs/_build/html' not found."
          exit 1
        fi
        touch _site/.nojekyll
        echo "webllm.mlc.ai" > _site/CNAME

        # Deploy ke branch gh-pages
        git fetch origin
        git switch --create gh-pages || git switch gh-pages
        rm -rf ./*
        cp -r _site/* .
        git add .
        git commit -m "Deploy site on $(date)"
        git push --force origin gh-pages

    - name: Cleanup
      if: always()
      run: git switch main
