name: Build site and push to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configuring build Environment
      run: |
        sudo apt-get update
        python -m pip install -U pip

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Installing dependencies
      run: |
        python -m pip install -r docs/requirements.txt
        gem install jekyll jekyll-remote-theme jekyll-sass-converter

    - name: Build and deploy site
      if: github.ref == 'refs/heads/main'
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.MLC_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git config --global user.email "mlc-gh-actions-bot@nomail"
        git config --global user.name "mlc-gh-actions-bot"
        
        git fetch origin
        
        # Cek apakah branch gh-pages sudah ada
        if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
          git checkout gh-pages
        else
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initialize gh-pages branch"
          git push origin gh-pages
        fi

        # Jalankan script untuk deploy
        ./scripts/gh_deploy_site.sh
